server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.113.221.249:3306/db_springboot-vue?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    url: jdbc:mysql://localhost:3306/db_springboot-vue?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    #url: jdbc:mysql://localhost:3306/springboot-vue?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
#    时间格式化
#  jackson:
#    date-format: yyyy-MM-dd
#    设置mybatis-plus 日志输出信息
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl